fix(boot): Make sure Setup has been cloned in /home/brieuc before bootstraping.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,6 +3,16 @@ set -euo pipefail
 
 # This script is the main entry point to bootstrap a new computer
 
+DIR=$(dirname $0)
+SETUP_ROOT_DIR=$(realpath $DIR)
+SETUP_PKGS_DIR="$SETUP_ROOT_DIR/Pkgs"
+
+# Check that the Setup repo has been cloned into $HOME/<some_dir>
+SETUP_PARENT_DIR=$(dirname $SETUP_ROOT_DIR)
+if [ "$SETUP_PARENT_DIR" != "$HOME" ] ; then
+  echo "error: Setup must be cloned into your $HOME directory." >&2 ; exit 1
+fi
+
 # Install required packages
 # TODO: Use apt or dpkg to check whether a Debian package is installed.
 REQ_PKG="cmake curl gcc gdb git jq lazygit make kitty stow wget xsel"
@@ -17,18 +27,14 @@ for pkg in $REQ_PKG ; do
 done
 
 if [[ ${#MISSING_PKG[@]} -gt 0 ]] ; then
-  echo "info: Installing missing package(s): ${MISSING_PKG[*]}"
+  echo "info : Installing missing package(s): ${MISSING_PKG[*]}"
   sudo apt install "${MISSING_PKG[@]}"
 fi
 
 # Bootstrapping
-DIR=$(dirname $0)
-SETUP_ROOT_DIR=$(realpath $DIR)
-SETUP_PKGS_DIR="$SETUP_ROOT_DIR/Pkgs"
-
-echo "info: bootstrapping system..."
-echo "info: SETUP_ROOT_DIR: $SETUP_ROOT_DIR"
-echo "info: SETUP_PKGS_DIR: $SETUP_PKGS_DIR"
+echo "info : bootstrapping system..."
+echo "info : SETUP_ROOT_DIR: $SETUP_ROOT_DIR"
+echo "info : SETUP_PKGS_DIR: $SETUP_PKGS_DIR"
 
 # Remove existing shell configuration files.
 [ -e "$HOME/.bashrc" ] && rm "$HOME/.bashrc" 
@@ -44,7 +50,7 @@ echo "export SETUP_PKGS_DIR=$SETUP_PKGS_DIR" >> "$HOME/.profile.d/setup.env"
 stow -S -d "$SETUP_PKGS_DIR" -t "$HOME" shell
 . "$HOME/.profile"
 
-echo "info: system has been bootstrapped. To setup additional modules:"
+echo "info : system has been bootstrapped. To setup additional modules:"
 echo "  '$ setup <module1>'"
 
 
